### ISSUE TITLE
fpccompatibilty error

### ISSUE THREAD

**Issue by roywd** [mse-org/mseide-msegui#29] opened 2021-07-05 21:15 UTC
error encountered compiling app, latest version 5.4.0
myprintsample.pas
  uses
   mseformatpngwrite
mseformatpngwrite.pas
  uses
   msefpwritepng

gives the error:
  mseformatpngwrite.pas(19,41) Fatal: Can't find unit msefpwritepng used by mseformatpngwrite

earlier version	3.8 works fine:

**Comment by fredvs** [comment] 2021-07-05 21:48
Hello Roywd.

Indeed, sorry for the inconvenance, when we renamed all fpimage files into msefpimage in /fpccompatibility, I forgot to add msefpwritepng.pp.

It is fixed in last commit 8ed86cfd4.

Thanks to note it.

Fre;D

**Comment by fredvs** [comment] 2021-07-05 22:48
Ooops, after deeper check, there were other files missing (for _mseformattiffwrite.pas_, _mseformatjpgwrite.pas_).

Fixed in last commit f7fca85

**Comment by fredvs** [comment] 2021-07-05 23:06
Re-ooops:it was also a error in classes vs mclasses in _msefpreadpng.pas_.

Fixed in last commit 2b2d92a

**Comment by fredvs** [comment] 2021-07-05 23:10
Hum and a other problem fixed: there was 2 msezstream.pas, one in /fpccompatibility and one in /crypto.
So renamed the first into mse_zstream.pas and changed with it in uses for all mse_fpimageXXX...

Fixed in last commit 097ca86

I think that a new release with those fixes will be needed.

**Comment by roywd** [comment] 2021-07-05 23:39
Many thanks!

that is a big help

will stick with an earlier version for now, but it is nice to know that
there is a fix - thought that
i may be doing something wrong

--roy

**Comment by fredvs** [comment] 2021-07-05 23:43
Hello.

You did find a big problem.
I hope that now all is fixed.

I only load image and did not try to write one.
So thanks that you try it.

I re-build all my mse applications with the last fixes and it seems to work ok.

It would be great if you try with your applications if all is ok with last commit.

Fre;D

**Comment by fredvs** [comment] 2021-07-05 23:44
> i may be doing something wrong

No, no, there was indeed problems.

**Comment by roywd** [comment] 2021-07-06 18:31
will try this and let you know what i find, thanks again for your work

**Comment by fredvs** [comment] 2021-07-06 18:55
Thanks.

By curiosity, when you compile your app with msegui version 3.8, what fpc version are you using?

Version 3.8 date is 2015-05-13.

Because with fpc 3.2.0 there should have problems, mainly on Unix.

**Comment by roywd** [comment] 2021-07-06 23:59
it was fpc 2.6.4

**Comment by fredvs** [comment] 2021-07-08 16:57
> it was fpc 2.6.4

Ha, ok.
With last commits it should work with fpc 2.6.4 too.

(IMHO fpc 2.6.4 is the best fpc version.  fpc 3.x.x has lot of bugs and breaks lot of things. But this is a other story.)

**Comment by roywd** [comment] 2021-07-08 17:27
will check out the commits and let you know

**Comment by fredvs** [comment] 2021-07-10 16:00
> will check out the commits and let you know

Super!
When you give the green light, I will do a new release with those last commits.

Thanks.

**Comment by roywd** [comment] 2021-07-10 23:35
this is what i have so far:
compiles fine
app starts up ok, showing the main screen
-but- when i open a display/view page then there is a problem
the page has a tree view plus a content view
selecting an item in the tree view should display details for that item in
the content view
what happens is some strange results on selecting tree items
the tree nodes seem to jump up to the top of the tree, hiding what is
already there
so after selecting a few tree items i have a whole bunch all sitting at the
top of the tree
now also, if i then press on a detail button which is supposed to open a
new edit page for the selected item
i get an error message, something like tbutton1 (which is in the edit page)
invalid property

if you like i could send you the app source code to demonstrate?

so far i have only checked the commits
have not  looked at earlier versions (after 3.8, before 5.6.0, eg 4.4, 4.6)

**Comment by fredvs** [comment] 2021-07-11 00:01
Hello.

It will be very useful if you can give code to demonstrate this.
Only to be sure, are you using msegui 3.8 ?
Because it date from 2015.

The last msegui release from Martin is 4.6.2, 03/11/2018. 

https://github.com/mse-org/mseide-msegui/tree/9206fd8982b22fd77df7b13c8d4d2c192a923f1b

But, yes, please, with code it will be much easier to understand the problem.

**Comment by fredvs** [comment] 2021-07-11 00:03
Huh, in previous post, please read "are you using msegui 3.8 ?" ( not fpgui 3.8)

**Comment by fredvs** [comment] 2021-07-11 00:10
Also, could you give your configuration, OS (Linux or Windows), 32 or 64 bit?
Thanks.

**Comment by fredvs** [comment] 2021-07-11 00:31
Re-hello.

I just check in "VERSION.TXT" about breaking compatibility with new release.
There are lot of breaking change from version 3.8:

> Version 4.6.2
> 2018-11-03
> 2018-10-15
>  tcustomframe.colorclient default value cl_transparent -> cl_default.
>  tdispframe default actualcolorclient() value cl_transparent -> cl_noedit.
> 2018-10-14
>  getsubformeventty and initsubformeventty sender parameter TObject->ttabpage.
> 2018-09-25
>  winidty = ptruint ->  winidty = type ptruint. Existing IDE generated
>  eventhandlers with winidty parameter (createwinideventty, destroywinideventty)
>  must be updated (longword/qword -> winidty).
> 2018-09-23
>  singlekeyshiftstatesmask -> shiftstatesrepeatmask.
> 2018-09-14
>  optiondockty od_childicons -> optionformty odf_childicons.
> 2018-09-12
>  tifi*clientcontroller.onvaluchanged properties are value type specific.
> 2017-12-22
>  iassistiveserver.doactionexecute() has iassistiveclient parameter.
>  iassistiveserver.dofocuschanged() has iassistiveclient parameter.
> 2017-12-17
>  iassitiveserver.clientmouseevent() -> doclientmouseevent()
> 2017-12-15
>  initializedynlib(),releasdynlib() callback has data pointer parameter.
> 
> Version 4.6
> 2017-11-23
> 2017-10-28 imagebufferinfoty -> maskedimagety.
> 2017-09-22
>  tdatabutton.min -> valuemin, max -> valuemax.
>  tintegeredit.min -> valuemin, max -> valuemax.
>  tint64edit.min -> valuemin, max -> valuemax.
>  tenumedit.min -> valuemin, max -> valuemax.
>  trealedit.min -> valuemin, max -> valuemax.
>  tdatetimeedit.min -> valuemin, max -> valuemax.
> 2017-09-14
>  Definition of the inner active area of buttons is made with
>  the new tframe property frameo_* instead of framei_*,
>  framei_* is used in order to adjust the caption rect.
>  ttabs.captionframe_* replaced by tframe.framei_*.
> 2017-07-13
>  Definition of "msestring" moved from "msestrings" to "msetypes".
> 2017-04-14
>  cellinfoty boolean flags replaced by celldrawstatesty set.
> 
> Version 4.4.2
> 2017-04-08
> 2017-04-03
>  cl_defaultrect -> cl_buttondefaultrect.
> 2017-03-30
>  Changed parameter clipandmove -> clip, move in
>  beforeframepaintbackgroundeventty and beforeframepaintbackgroundeventty.
> 2017-02-20
>  dno_append removed from tdbnavigator default options.
> 
> Version 4.4
> 2017-02-13
> 2017-01-29
>  tsqlresult.cols -> datacols.
> 2017-01-27 tlayouter.place_options plo_syncmaxautosize,
>  plo_synccaptiondistx,plo_synccaptiondisty,
>  plo_syncpaintwidth,plo_syncpaintheight ->
>  optionslayout lao_syncmaxautosize,
>  lao_synccaptiondistx,lao_synccaptiondisty,
>  lao_syncpaintwidth,lao_syncpaintheight.
> 2017-01-19
>  msefbconnection.pas -> msefb3connection.pas.
>  tfbconnection -> tfb3connection.
> 2016-12-26
>  timagelist.getimage returns bitmap- and maskbitmap-kind of imagelist.
> 2016-10-21
>  tlistitem.drawimage() parameter order changed.
> 2016-10-02
>  teditwidgetdatalink.options oed_syncedittonavigator default off.
> 2016-09-30
>  Options belonging to bufdataset descendants only moved from
>  tdscontroller.options to tmsebufdataset.options.
>  "delayedapplycount" tdscontroller -> tmsebufdataset.
> 2016-09-28
>  Frame buttons options fbo_disabled overrides readonly-state of widget.
>  For existing widgets which have been saved in readonly-state fbo_disabled must
>  be cleared one time in design mode.
> 2016-09-26
>  TCustomSQLConnection DatabaseName, Password, UserName, HostName, Charset and
>  Role properties ansistring -> msestring.
> 2016-27-04
>  ondrawcelleventty cellinfo parameter var instead of const.
> 
> Version 4.2
> 2016-02-24
> 2015-12-23
>  Endpoints of visible tframe.frameimage edges are always painted independently
>   of the hiddenedges state of neighbors. Copy the middle image to the end images
>   in order to restore the old appearance.
> 2015-11-23
>  twidget.findwidget() -> findchild().
>   twidget.findtagwidget() -> findtagchild().
> 
> Version 4.0
> 2015-11-13
> 2015-11-03
>  tcustomface opacity values of alpha blending inverted, white is
>   full opaqueness of the elements.
> 2015-10-27
>  tcustomframe.frameimage_offsetactivemouse,
>   frameimage_offsetactiveclicked, frameface_offsetactivemouse and
>   frameface_offsetactiveclicked removed. The resulting offset is now the sum
>   of all active offsets.
> 2015-10-24
>  tslider.scrollbar.face moved to tcustomscrollbar,
>   disable tslider.scrollbar.face in order to show the pattern.
> 
> Version 4.0beta1
> 2015-09-30
>  tfiledialog statvalues lastdir, filehistory, filefilter and fielefilterindext
>   moved to oe1_saveoptions section.
> 2015-09-27
>  charencodingty ce_utf8n -> ce_utf8, please load broken forms into MSEide
>   in order to fix the *.mfm files.
> 2015-09-15
>  Internal character encoding is utf-16 instead of UCS2.
> 2015-08-09
>  applyrecupdateeventty asql parameter is msestring.
> 2015-08-08
>  trystrto*mse() -> trystrto*().
> 2015-07-02
>  Commandline functions and params use msestring instead of string.
 
It is possible that one of the new version has broken some compatibility with your code.

But this could be easily be fixed (if you give your code I will do it with pleasure). 

From version 5.0.0. no more break of compatibility was done (only make it compatible with fpc >= 2.6.4) and add some new features.

**Comment by fredvs** [comment] 2021-07-13 15:08
Hello.

Maybe you could try this (found in a Lazarus forum)
https://forum.lazarus.freepascal.org/index.php?topic=31996.msg205826#msg205826

>  « Reply #5 on: March 19, 2016, 04:59:47 pm »
> Quote from: airpas on March 19, 2016, 12:06:22 pm
> 
      msegui/ide is good as a lightweight rad with a nice set of components,
      but has some drak sides : the project file is not backword compatible
      (if u have a project made with the version 3 , then it probably wont work with the new 4.2 ) ,

> If stored properties of MSEgui components change I add code which automatically converts old *.mfm's while loading. Please load all forms in the new MSEide, RightClick-'Touch all forms' in one of the forms, 'File'-'Save all', that will write updated *.mfm files to disk.
> If the conversion code is expensive I remove it after some MSEgui versions. If one loads an incompatible form afterwards the *.mfm file will be opened in source editor for manual fix-up. Often it is enough to delete the problematic rows.
> IIRC the last time I removed conversion code was before MSEide+MSEgui version 3.0.
>

**Comment by roywd** [comment] 2021-07-14 17:46
Thanks for the suggestion

Have tried this, but so far does not help

Next will build a minimal project to try to demonstrate the issues
and then send in the source code

**Comment by roywd** [comment] 2021-07-18 14:06
the attached sample i believe shows one problem...
this appears to work fine with earlier versions of msegui, but not in
latest commits

**Comment by fredvs** [comment] 2021-07-18 14:08
Hello.
Many thanks but I dont see the attached sample, where is it?

**Comment by fredvs** [comment] 2021-07-18 14:10
You may use the Github issue and add a file (not zip, only tar) by dragging.
https://github.com/mse-org/mseide-msegui/issues/29

**Comment by roywd** [comment] 2021-07-18 15:57
maybe i got this wrong, but i thought i had attached the files...
confirmed this by looking at the sent mail, which included about 8 files
did you see no files?
my understanding is that one could get the attachments, and compile and run
using mseide

**Comment by fredvs** [comment] 2021-07-18 16:13
No, sorry, I dont see any attachment.

What software are you using to sent the issue-message?
Maybe you could take a look about your issue via the web Github issue site:
https://github.com/mse-org/mseide-msegui/issues/

And attach the files by dragging, selecting or pasting there.

**Comment by fredvs** [comment] 2021-07-18 16:46
> my understanding is that one could get the attachments, and compile and run using mseide

Yes, it is that but to compile and run I need the source that are in the attachment.
But I dont see that attachment.

**Comment by roywd** [comment] 2021-07-18 17:21
was trying to send the files via gmail

**Comment by fredvs** [comment] 2021-07-18 17:25
Ha ok.

With gmail, I dont know but via hotmail it does not work to add attachment.
It seems that GitHub only accept attachment via the site https://github.com/mse-org/mseide-msegui/issues.

**Comment by roywd** [comment] 2021-07-18 17:46
problem is i tried to attach the files in the github site but im afraid im
too stupid to do it properly -
i ended up with nothing
i tried to do this: drag one of the files to the issues but this did not
appear there

**Comment by fredvs** [comment] 2021-07-18 18:25
Hello.

Go in the end of the page.
There is a "Write/Preview" panel.

Then drag drop your files inside the "Write" tab.

Then click on green button "Comment".

This all.

**Comment by fredvs** [comment] 2021-07-18 20:40
Of course, you need first to login to github with your @roywd account to be able to sent comment-attachment.

**Comment by fredvs** [comment] 2021-07-18 20:44
Here to sign-in:
https://github.com/login

**Comment by JonnyTech** [comment] 2021-07-19 11:26
You cannot post attachments via email:

https://github.blog/2011-03-10-reply-to-comments-from-email/

> Email attachments are currently ignored.

**Comment by roywd** [comment] 2021-07-19 17:36
[demo6.zip](https://github.com/mse-org/mseide-msegui/files/6842843/demo6.zip)

**Comment by fredvs** [comment] 2021-07-19 18:33
Yep, this time I see and get it!
;-)
OK, I will jump inside it asap (hyper busy this week).

Write you later.

**Comment by fredvs** [comment] 2021-07-19 21:44
Hello @roywd

OK, I did jump into your demo.
Indeed, it seems that the old twidgetgrid is no more compatible with last releases.
[EDIT] No, see my next post, the problem is with arrows.
 
So, in your project, I first move ttreeitemedit1 from the twidgetgrid1 to the main form ( Ctrl+X to Cut, then Ctrl+V to paste) .
Then deleted twidgetgrid1 and recreated a new one with the component palette.
Then re-move the ttreeitemedit1 from the main form (Ctrl+X to Cut) to the first column of the new twidgetgrid1 Ctrl+V to paste).

In your demo there is no fixed row, so fixcols.count  was set to 0.

And all seems ok now.

In attachment your demo updated for msegui 5.6.2.
Could you try it with last source of  msegui 5.6.2?
It should work with fpc 2.6.4, 3.0.0, 3.2.0, 3.2.2, 3.3.1.

Fre;D

[EDIT] There is no need to delete the grid and re-create it, see my next post.

[demo6_msegui56.zip](https://github.com/mse-org/mseide-msegui/files/6844453/demo6_msegui56.zip)

**Comment by fredvs** [comment] 2021-07-20 01:15
Re-Hello @roywd
I did re-check your demo and the problem comes from the anchors set in _ttreeitemedit1_.

Just set the anchors to _[an_left,an_top]_ and _bounds.cy := 19_.

See the Object inspector.

![treeview](https://user-images.githubusercontent.com/3421249/126247178-6898e446-bd4e-4cc9-b20a-bd26e66789cc.png)

So you even do not need to delete-grid and re-paste.
The only problem was the arrows in _ttreeitemedit1_.

To resume, it seems that the problems of compatibility in your demo are the arrows.
Maybe the behavior of older release for the parameters of arrows was different.

Fre;D

**Comment by roywd** [comment] 2021-07-20 14:53
Thanks so much for looking into this and for your insight

will try this out and see what i get

**Comment by roywd** [comment] 2021-07-20 18:25
have tried this, and looking good so far!

thanks once again for your quick response, and in spotting the problems

will keep you posted of other things i may find as i try out more code

**Comment by fredvs** [comment] 2021-10-29 22:54
Closed because no cry...

**Closed as completed** 2021-10-29 22:54 UTC
Labels: bug, good first issue, probably fixed
